[package]
name = "send_save_data_program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=3.0.0"
borsh = { version = "1.5.7", features = ["derive"] }
base64ct = "=1.6.0"

[lib]
crate-type = ["cdylib", "lib"]
